### ISSUE TITLE
Extract images using ffmpeg

### ISSUE THREAD

**Issue by Qiliqing** [ZeldaM1/SR-ITM-GAN#1]
Hi @ZeldaM1 

I got an error when using ffmpeg to extract images from HDR_4K.mp4/SDR_4K.mp4
![image](https://user-images.githubusercontent.com/35137285/101763015-2374a400-3b19-11eb-9501-ffaafb0d66e3.png)

I can successfully extract the image from ***_1080.mp4. Is there something wrong with the ***_4K.mp4 file ？

**Comment by ZeldaM1** [comment]
Hi @Qiliqing, 
I tested the 4k.mp4 file on my computer with FFMPEG and successfully extracted images. The following tips for using FFMPEG may be useful: 1. providing absolute paths instead of relative paths in your command. 2. using forward slash '/' instead of backward slash '\' to avoid escape character. 3. check filename and make sure you type in correctly.
Still, if you can't extract images with tips above, please contact me to update HDR_4K.mp4 file.

Best,
ZeldaM

**Comment by ZeldaM1** [comment]
Hi @Qiliqing, 
I tested the 4k.mp4 file on my computer with FFMPEG and successfully extracted images. The following tips for using FFMPEG may be useful: 1. providing absolute paths instead of relative paths in your command. 2. using forward slash '/' instead of backward slash  '\' to avoid escape character. 3. check filename and make sure you type in correctly.
Still, if you can't extract images with tips above, please contact me to update HDR_4K.mp4 file.

Best,
ZeldaM

**Comment by Qiliqing** [comment]
Hi @ZeldaM1 ，
I downloaded 4K.mp4 files again on Baidu Cloud and tried above sugesstions. There is same error like before: 

![image](https://user-images.githubusercontent.com/35137285/102304538-a1f99780-3f98-11eb-983c-a88533a77c1c.png)

This means that 4K.mp4 is a broken mp4 file, it may be due to some errors in uploading or downloading the 4K.mp4 file. **I suggest that you can compress the video into a rar file and then upload it to the cloud disk.** By the way, I can't open the link to Google drive because it says I should ask the owner for access.

Best,
Qiliqing

**Comment by ZeldaM1** [comment]
> Hi @ZeldaM1 ，
> I downloaded 4K.mp4 files again on Baidu Cloud and tried above sugesstions. There is same error like before:
> 
> ![image](https://user-images.githubusercontent.com/35137285/102304538-a1f99780-3f98-11eb-983c-a88533a77c1c.png)
> 
> This means that 4K.mp4 is a broken mp4 file, it may be due to some errors in uploading or downloading the 4K.mp4 file. **I suggest that you can compress the video into a rar file and then upload it to the cloud disk.** By the way, I can't open the link to Google drive because it says I should ask the owner for access.
> 
> Best,
> Qiliqing

Hi, I've already updated files of 4K folder and successfully extracted on my computer. Google Drive link is also available now. Please notice that this dataset could be very large(total 23229 images), enough space should be left for it. 
Also, since we provide SDR-HDR pair of the same size, further down-sampling should be operated on SDRs if SR models are applied here.

**Comment by Amy-zhang-yuanyuan** [comment]
Hi @ZeldaM1 
I encountered the following problem while creating lmdb files.  
![图片](https://user-images.githubusercontent.com/73935376/122323891-6c8b3200-cf5a-11eb-8ff9-5725600bd2a2.png)

Best
Zhangyuanyuan

**Comment by ZeldaM1** [comment]
> Hi @ZeldaM1
> I encountered the following problem while creating lmdb files.
> ![图片](https://user-images.githubusercontent.com/73935376/122323891-6c8b3200-cf5a-11eb-8ff9-5725600bd2a2.png)
> 
> Best
> Zhangyuanyuan

Hi, this may caused by your own data structure. Further DEBUG should be done on variable **all_img_list**. Please refer to [BasicSR](https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation_CN.md) for more details.
